In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ## Ruta

ruta_in = 'C:/Users/llore/R/Proyectos/Sunat/OSCE/'

# ## Convocatorias

convocatorias_2019 = pd.read_excel(ruta_in + '1. CONOSCE_CONVOCATORIAS2019_0.xlsx')
convocatorias_2020 = pd.read_excel(ruta_in + '1. CONOSCE_CONVOCATORIAS2020_0703.xlsx')
convocatorias_2021 = pd.read_excel(ruta_in + '1. CONOSCE_CONVOCATORIAS2021_0.xlsx')
convocatorias_2022 = pd.read_excel(ruta_in + '1. CONOSCE_CONVOCATORIAS2022_0.xlsx')
convocatorias_2023 = pd.read_excel(ruta_in + '1. CONOSCE_CONVOCATORIAS2023_0.xlsx')

convocatorias = pd.concat([convocatorias_2019, convocatorias_2020, convocatorias_2021, convocatorias_2022, convocatorias_2023])
del([convocatorias_2019, convocatorias_2020, convocatorias_2021, convocatorias_2022, convocatorias_2023])

convocatorias['idx'] = convocatorias['CODIGOCONVOCATORIA'].astype(str).str.cat(convocatorias['N_ITEM'].astype(str), sep='-')

In [12]:
# Filtrar los datos una vez y almacenarlos en una variable
datos_filtrados = convocatorias[['CODIGOCONVOCATORIA', 'MONTOREFERENCIAL']]

# Obtener los valores únicos de la columna 'CODIGOCONVOCATORIA'
valores_unicos = datos_filtrados['CODIGOCONVOCATORIA'].unique()

# Crear el histograma para cada valor único de 'CODIGOCONVOCATORIA'
plt.figure(figsize=(10, 6))
for codigo in valores_unicos:
    datos = datos_filtrados[datos_filtrados['CODIGOCONVOCATORIA'] == codigo]['MONTOREFERENCIAL']
    plt.hist(datos, bins=30, alpha=0.5, label=f'CODIGOCONVOCATORIA {codigo}')

plt.xlabel('MONTOREFERENCIAL')
plt.ylabel('Frecuencia')
plt.title('Histograma de MONTOREFERENCIAL por CODIGOCONVOCATORIA')
plt.legend()
plt.grid(True)
plt.show()

In [7]:
#!/usr/bin/env python
# coding: utf-8

# ## Librerias

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ## Ruta

ruta_in = 'C:/Users/llore/R/Proyectos/Sunat/OSCE/'

# ## Convocatorias

convocatorias_2019 = pd.read_excel(ruta_in + '1. CONOSCE_CONVOCATORIAS2019_0.xlsx')
convocatorias_2020 = pd.read_excel(ruta_in + '1. CONOSCE_CONVOCATORIAS2020_0703.xlsx')
convocatorias_2021 = pd.read_excel(ruta_in + '1. CONOSCE_CONVOCATORIAS2021_0.xlsx')
convocatorias_2022 = pd.read_excel(ruta_in + '1. CONOSCE_CONVOCATORIAS2022_0.xlsx')
convocatorias_2023 = pd.read_excel(ruta_in + '1. CONOSCE_CONVOCATORIAS2023_0.xlsx')

convocatorias = pd.concat([convocatorias_2019, convocatorias_2020, convocatorias_2021, convocatorias_2022, convocatorias_2023])
del([convocatorias_2019, convocatorias_2020, convocatorias_2021, convocatorias_2022, convocatorias_2023])

convocatorias['idx'] = convocatorias['CODIGOCONVOCATORIA'].astype(str).str.cat(convocatorias['N_ITEM'].astype(str), sep='-')

# ## Postores

postores_2019 = pd.read_excel(ruta_in + '2. CONOSCE_POSTOR2019_0.xlsx')
postores_2020 = pd.read_excel(ruta_in + '2. CONOSCE_POSTOR2020_0703.xlsx')
postores_2021 = pd.read_excel(ruta_in + '2. CONOSCE_POSTOR2021_0.xlsx')
postores_2022 = pd.read_excel(ruta_in + '2. CONOSCE_POSTOR2022_0.xlsx')
postores_2023 = pd.read_excel(ruta_in + '2. CONOSCE_POSTOR2023_0.xlsx')

postores = pd.concat([postores_2019, postores_2020, postores_2021, postores_2022, postores_2023])
del([postores_2019, postores_2020, postores_2021, postores_2022, postores_2023])

postores['idx'] = postores['CODIGO_CONVOCATORIA'].astype(str).str.cat(postores['N_ITEM'].astype(str), sep='-')

# ## Adjudicados

adjudicados_2019 = pd.read_excel(ruta_in + '3. CONOSCE_ADJUDICACIONES2019_0.xlsx')
adjudicados_2020 = pd.read_excel(ruta_in + '3. CONOSCE_ADJUDICACIONES2020_0703.xlsx')
adjudicados_2021 = pd.read_excel(ruta_in + '3. CONOSCE_ADJUDICACIONES2021_0.xlsx')
adjudicados_2022 = pd.read_excel(ruta_in + '3. CONOSCE_ADJUDICACIONES2022_0.xlsx')
adjudicados_2023 = pd.read_excel(ruta_in + '3. CONOSCE_ADJUDICACIONES2023_0.xlsx')

adjudicados = pd.concat([adjudicados_2019, adjudicados_2020, adjudicados_2021, adjudicados_2022, adjudicados_2023])
del([adjudicados_2019, adjudicados_2020, adjudicados_2021, adjudicados_2022, adjudicados_2023])

adjudicados['idx'] = adjudicados['CODIGOCONVOCATORIA'].astype(str).str.cat(adjudicados['N_ITEM'].astype(str), sep='-')

# Agregar una nueva columna 'ADJUDICADO' en la base de datos 'adjudicados'
adjudicados['ADJUDICADO'] = 0

# Recorrer cada fila de la base de datos
for index, row in adjudicados.iterrows():
    # Si el estado del ítem es 'ADJUDICADO', marcar como 1 en la columna 'ADJUDICADO'
    if row['ESTADO_ITEM'] == 'Contratado':
        adjudicados.at[index, 'ADJUDICADO'] = 1

## Contratos

contratos_2019 = pd.read_excel(ruta_in + '5. CONOSCE_CONTRATOS2019_0.xlsx')
contratos_2020 = pd.read_excel(ruta_in + '5. CONOSCE_CONTRATOS2020_0703.xlsx')
contratos_2021 = pd.read_excel(ruta_in + '5. CONOSCE_CONTRATOS2021_0.xlsx')
contratos_2022 = pd.read_excel(ruta_in + '5. CONOSCE_CONTRATOS2022_0.xlsx')
contratos_2023 = pd.read_excel(ruta_in + '5. CONOSCE_CONTRATOS2023_0.xlsx')

contratos = pd.concat([contratos_2019, contratos_2020, contratos_2021, contratos_2022, contratos_2023])
del([contratos_2019, contratos_2020, contratos_2021, contratos_2022, contratos_2023])

contratos['idx'] = contratos['CODIGOCONVOCATORIA'].astype(str).str.cat(contratos['NUM_ITEM'].astype(str), sep='-')

# Fusionar las bases de datos 'adjudicados' y 'contratos' por las columnas 'CODIGOCONVOCATORIA' y 'N_ITEM'/'NUM_ITEM'
merged_df = pd.merge(adjudicados, contratos, left_on=['CODIGOCONVOCATORIA', 'N_ITEM'], right_on=['CODIGOCONVOCATORIA', 'NUM_ITEM'], how='inner')

# Agregar una nueva columna 'CONTRATADO' en la base de datos fusionada
merged_df['CONTRATADO'] = 0

# Recorrer cada fila de la base de datos fusionada
for index, row in merged_df.iterrows():
    # Si 'ADJUDICADO' es 1 y el 'TIENERESOLUCION' es True, marcar como 1 en la columna 'CONTRATADO'
    if row['ADJUDICADO'] == 1 and row['TIENERESOLUCION']:
        merged_df.at[index, 'CONTRATADO'] = 1

In [9]:
merged_df.tail(5)

,CODIGOENTIDAD_x,ENTIDAD_RUC,CODIGOCONVOCATORIA,PROCESO,N_ITEM,DESCRIPCION_ITEM,ESTADO_ITEM,CANTIDAD_ADJUDICADO_ITEM,MONTO_REFERENCIAL_ITEM,MONTO_ADJUDICADO_ITEM,...,MONTO_COMPLEMENTARIO,URLCONTRATO,CODIGOENTIDAD_y,NUM_ITEM,MONEDA_y,RUC_CONTRATISTA,RUC_DESTINATARIO_PAGO,TIENERESOLUCION,idx_y,CONTRATADO
342807,200825,20556118079,967787,AS-DU-034-2023-SM-4-2023-UE:026-DIREICAJ-2,1,MOTOCICLETA TODO TERRENO,Contratado,15.0,722040.00,718957.5,...,NaN,https://prodapp2.seace.gob.pe/portalseace-uiwd...,200825,1,Soles,20100821371,20536429183,NO,967787-1,1
342808,1343,20131369043,939862,AS-SM-17-2023-MDSA/CS-1,2,"ADQUISICI¿N DE INSUMOS, (LECHE EVAPORADA ENTER...",Contratado,32462.0,144780.52,132834.5,...,NaN,https://prodapp2.seace.gob.pe/portalseace-uiwd...,1343,2,Soles,20600989040,20600989040,NO,939862-2,1
342809,822,20317337150,970522,AS-SM-202-2023-MDP/CS-1,1,ADQUISICION DE RODILLO COMPACTADORA PARA EL PR...,Contratado,1.0,73855.00,73850.0,...,NaN,https://prodapp2.seace.gob.pe/portalseace-uiwd...,822,1,Soles,20608520491,20608520491,NO,970522-1,1
342810,200175,20452726999,968494,COMPRE-SM-3-2023-RSI-1,1,MICROSCOPIO BINOCULAR Y OCULAR DE 10 X PARA FL...,Contratado,3.0,64215.00,64215.0,...,NaN,https://prodapp2.seace.gob.pe/portalseace-uiwd...,200175,1,Soles,20600853059,20600853059,NO,968494-1,1
342811,2381,20102762925,984321,DIRECTA-PROC-3-2023-EPS GRAU SA-GG-1,1,"MEDIDORES DE 1/2"" DE DIAMETRO INCLUIDO ACCESOR...",Contratado,3200.0,868480.00,868480.0,...,NaN,https://prodapp2.seace.gob.pe/portalseace-uiwd...,2381,1,Soles,1489223,20606961261,NO,984321-1,1

In [10]:
merged_df.shape

(342812, 44)